### PR TITLE
lbpEnvVer parity (somewhat, GameServer) and player polaroid resolution fix (Website)

### LINKED ISSUE #363: lbpEnvVer too long
The server name is sent along with the rest of the auth stuff in the LITTLEBIGPLANETPS3_XML/login response in the lbpEnvVer tag.
The exclusion of this makes the server show up as unknown in LBP2 br2_r47518 and other mspf enabled builds.

### LINKED ISSUE #368: [website] set background-size css property on user cards
currently if a profile picture for a user is larger than 100x100 it'll get cropped to 100x100 rather than scaled down.

### PR DESCRIPTION
**Pull request by TorutheRedFox**
adds option to customize envver

Closes #363
Closes #368

it's now formatted like the official servers: 'env-name' {'branch-if-not-main'_}r'revision'

revision format and environment name can be changed in the config
by default it's commithash_buildtype, but it can also be commit number if admin prefers it that way, making the default envver string be something like this: lighthouse rdc81d8fc_Release

### CODE REVIEW

File: ProjectLighthouse/Helpers/VersionHelper.cs [hunk 1]
```diff
@@ -48,13 +51,16 @@ static VersionHelper()
...
+            Revision = $"{Branch}-dirty_r{rawRevision}";
             CanCheckForUpdates = false;
         }
     }
 
     public static string CommitHash { get; set; }
     public static string Branch { get; set; }
-    public static string FullVersion => $"Project Lighthouse {Branch}@{CommitHash} {Build} ({ServerConfiguration.Instance.Customization.ServerName})";
+    public static string Revision { get; set; }
+    public static string EnvVer => $"{ServerConfiguration.Instance.Customization.EnvironmentName} {Revision}";
```
Comment (jvyden) [inline ProjectLighthouse/Helpers/VersionHelper.cs:62]: This variable name is a little unclear...

Perhaps renaming it to something like `ShortVersion`/`BrandVersion` or adding some XMLDoc could help?

File: ProjectLighthouse.Servers.GameServer/Controllers/NewsController.cs [hunk 2]
```diff
@@ -0,0 +1,36 @@
+﻿using LBPUnion.ProjectLighthouse.Serialization;
+using static LBPUnion.ProjectLighthouse.Types.News.News;
+using Microsoft.AspNetCore.Mvc;
+
+namespace LBPUnion.ProjectLighthouse.Controllers;
+
+[ApiController]
+[Route("LITTLEBIGPLANETPS3_XML/news")]
+[Produces("text/xml")]
+public class NewsController : ControllerBase
```
Comment (jvyden) [inline ProjectLighthouse.Servers.GameServer/Controllers/NewsController.cs:10]: Not a fan of news being re-implemented here in a scuffed state; I would rather this be added when complete.

File: ProjectLighthouse/Helpers/VersionHelper.cs [hunk 3]
```diff
@@ -48,13 +51,16 @@ static VersionHelper()
...
+    public static string FullVersion => $"Project Lighthouse {Branch}@{CommitHash} {Build} ({EnvVer})";
```
Comment (jvyden) [inline ProjectLighthouse/Helpers/VersionHelper.cs:63]: Including `EnvVer` here causes redundant info to display. The old way is better IMO:

```suggestion
    public static string FullVersion => $"Project Lighthouse {Branch}@{CommitHash} {Build} ({ServerConfiguration.Instance.Customization.ServerName})";
```

File: ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs [hunk 4]
```diff
@@ -3,4 +3,6 @@ namespace LBPUnion.ProjectLighthouse.Configuration.ConfigurationCategories;
 public class CustomizationConfiguration
 {
     public string ServerName { get; set; } = "Project Lighthouse";
+    public string EnvironmentName { get; set; } = "lighthouse";
+    public bool UseNumericRevisionNumber { get; set; } = false;
```
Comment (jvyden) [inline ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs:7]: Using the revision count is never going to be reliable; shallow clones exist and are used frequently with CI systems (both GitHub Actions and Gitlab CI only clone up to 20 commits)

I once again strongly against using revision counts; hashes are better in every way. If readability is a problem, it may be worth trimming the number of characters from 8 to about 6.

File: ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs [hunk 5]
```diff
@@ -3,4 +3,6 @@ namespace LBPUnion.ProjectLighthouse.Configuration.ConfigurationCategories;
 public class CustomizationConfiguration
 {
     public string ServerName { get; set; } = "Project Lighthouse";
+    public string EnvironmentName { get; set; } = "lighthouse";
```
Comment (jvyden) [inline ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs:6]:
```suggestion
    public string EnvironmentName { get; set; } = "ProjectLighthouse";
```

File: ProjectLighthouse.Servers.Website/Pages/Partials/UserCardPartial.cshtml [hunk 6]
```diff
@@ -9,7 +9,7 @@
     @{
         int size = isMobile ? 50 : 100;
     }
-    <div class="cardIcon userCardIcon" style="background-image: url('/gameAssets/@Model.WebsiteAvatarHash'); min-width: @(size)px; width: @(size)px; height: @(size)px">
+    <div class="cardIcon userCardIcon" style="background-image: url('/gameAssets/@Model.WebsiteAvatarHash'); min-width: @(size)px; width: @(size)px; height: @(size)px; background-position: center center; background-size: auto @(size)px;">
```
Comment (jvyden) [inline ProjectLighthouse.Servers.Website/Pages/Partials/UserCardPartial.cshtml:12]: This should be moved to a CSS file. This is starting to get a little ridiculous, lol.

**Review by jvyden — CHANGES_REQUESTED** [review]
Hello, thank you for your contribution towards Project Lighthouse!

A few concerns about the contents of this MR...

File: ProjectLighthouse.Servers.GameServer/Controllers/NewsController.cs (hunk 2 above)
Comment (TorutheRedFox) [reply ProjectLighthouse.Servers.GameServer/Controllers/NewsController.cs:10]: oh that was for testing, I'll remove it

File: ProjectLighthouse/Helpers/VersionHelper.cs (hunk 3 above)
Comment (TorutheRedFox) [reply ProjectLighthouse/Helpers/VersionHelper.cs:63]: It displaying the envname is probably a bit better as well, displaying the name is a bit redundant too (especially on the site when you're told it in the title and homepage's header)

but yeah, displaying the hash and build in the default mode is a bit redundant

Comment (jvyden) [reply ProjectLighthouse/Helpers/VersionHelper.cs:63]: Honestly we might be fine without the brand at all

File: ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs (hunk 4 above)
Comment (TorutheRedFox) [reply ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs:7]: issues like this are entirely why it's optional and it's just for preference if you can facilitate the use of numeric revisions

I guess I can add a disclaimer in the envver that it's built from a shallow clone, or disable the functionality and throw a warning in the console that shallow clone builds don't support numeric versioning?

File: ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs (hunk 5 above)
Comment (TorutheRedFox) [reply ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs:6]: would project-lighthouse suit better?

it's more like official server naming

Comment (jvyden) [reply ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs:6]: Yeah; should be fine.

File: ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs (hunk 4 above)
Comment (jvyden) [reply ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs:7]: It's better and easier to just not have the option due to feature creep/bloat.

You're welcome to keep this functionality in a fork if you really want it, but it doesn't belong in the main repo.

Comment (TorutheRedFox) [reply ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs]: it's kinda a balancing act between the end user being able to tell easier that the server's been updated, and reliability.

File: ProjectLighthouse/Helpers/VersionHelper.cs (hunk 1 above)
Comment (TorutheRedFox) [reply ProjectLighthouse/Helpers/VersionHelper.cs]: is the way it currently is fine?

File: ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs (hunk 4 above)
Comment (jvyden) [reply ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs]: That is what a versioning system like SemVer (which is also a bit more clear) can provide. It will be added when Lighthouse gets closer to release.

I'm going to be brutally honest; this is the hill I will die on. Please remove this.

File: ProjectLighthouse/Helpers/VersionHelper.cs (hunk 1 above)
Comment (jvyden) [reply ProjectLighthouse/Helpers/VersionHelper.cs]: XMLDoc example:
```csharp
/// <summary>
/// The server's branding to show to LBP clients. Shows the environment name next to the revision.
/// </summary>
 public static string BrandVersion => "";
```

That way, you can hover over a reference to that variable and it will show you the summary.

This is in opposition to a comment; where you first have to know that it's there and you have to go to the class to look at it.

Comment (TorutheRedFox) [reply ProjectLighthouse/Helpers/VersionHelper.cs]: hold on which variable are you talking about exactly?

it's not telling me exactly which line you're talking about

Comment (jvyden) [reply ProjectLighthouse/Helpers/VersionHelper.cs]: `EnvVer`.

File: ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs (hunk 4 above)
Comment (TorutheRedFox) [reply ProjectLighthouse/Configuration/ConfigurationCategories/CustomizationConfiguration.cs]: I will once I finish testing other changes as I personally use this.

File: ProjectLighthouse/Helpers/VersionHelper.cs (hunk 1 above)
Comment (TorutheRedFox) [reply ProjectLighthouse/Helpers/VersionHelper.cs]: documented both

**Review by TorutheRedFox — COMMENTED** [review]
fixed I think

File: ProjectLighthouse/ProjectLighthouse.csproj [hunk 7]
```diff
@@ -59,7 +59,7 @@
     </ItemGroup>
 
     <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
-        <Exec Command="git describe --long --always --dirty --exclude=\* --abbrev=8 &gt; &quot;$(ProjectDir)/gitVersion.txt&quot;" />
+		<Exec Command="git rev-list HEAD --count &gt; &quot;$(ProjectDir)/gitRevCount.txt&quot;" />
```
Comment (jvyden) [inline ProjectLighthouse/ProjectLighthouse.csproj:62]:
```suggestion
```

File: ProjectLighthouse/Helpers/VersionHelper.cs [hunk 8]
```diff
@@ -54,7 +57,16 @@ static VersionHelper()
 
     public static string CommitHash { get; set; }
     public static string Branch { get; set; }
-    public static string FullVersion => $"Project Lighthouse {Branch}@{CommitHash} {Build} ({ServerConfiguration.Instance.Customization.ServerName})";
+    /// <summary>
+    /// The amount of commits that currently exist in the local copy of the Git repository.
+    /// Not reliable as versioning if shallow cloning is used, with using the hash of the current commit being more reliable in that case.
+    /// </summary>
+    public static string OrdinalCommitNumber { get; set; }
```
Comment (jvyden) [inline ProjectLighthouse/Helpers/VersionHelper.cs:64]: I'd rename this variable to `FullCommitName` or something...

File: ProjectLighthouse/Helpers/VersionHelper.cs [hunk 9]
```diff
@@ -8,10 +8,13 @@ public static class VersionHelper
 {
     static VersionHelper()
     {
+        string commitNumber = "invalid";
         try
         {
             CommitHash = ResourceHelper.ReadManifestFile("gitVersion.txt");
             Branch = ResourceHelper.ReadManifestFile("gitBranch.txt");
+            commitNumber = $"{CommitHash}_{Build}";
+            OrdinalCommitNumber = (Branch == "main") ? $"r{commitNumber}" : $"{Branch}_r{commitNumber}";
```
Comment (jvyden) [inline ProjectLighthouse/Helpers/VersionHelper.cs:17]:
```suggestion
        string commitName = "invalid";
        try
        {
            CommitHash = ResourceHelper.ReadManifestFile("gitVersion.txt");
            Branch = ResourceHelper.ReadManifestFile("gitBranch.txt");
            
            commitName = $"{CommitHash}_{Build}";
            FullCommitName = (Branch == "main") ? $"r{commitName}" : $"{Branch}_r{commitName}";
```

**Review by jvyden — CHANGES_REQUESTED** [review]
Hmm, there's a couple of traces of the old system which may be confusing, have a look at these suggestions.

File: ProjectLighthouse/ProjectLighthouse.csproj (hunk 7 above)
Comment (TorutheRedFox) [reply ProjectLighthouse/ProjectLighthouse.csproj]: oops wrong line lol, fixed

**Comment by TorutheRedFox** [comment]
yeah either forgot about those or removed the wrong line xd

**Review by jvyden — APPROVED** [review]
I'll take it. Thank you for your contribution to Project Lighthouse!
