### PR TITLE
Base64 encode auth tokens

### LINKED ISSUE #1023: Email tokens not url encoded
**Describe the bug**
When emails are sent that involve tokens they should ideally be url encoded as that's what a url expects.

**To Reproduce**
1. Request any email that uses a token (password reset, or email verification)
2. look at the email and note the token on the end of the url, it's not url encoded

**Expected behavior**
Links should be either url encoded or only contain plain text

**Environment Details**
 - an email client, it's fairly universal.

### PR DESCRIPTION
**Pull request by Zaprit**
Base64 encode auth tokens to make them more URL compatible, i.e when they are used in emails.

Fixes #1023

### CODE REVIEW

File: ProjectLighthouse/Helpers/CryptoHelper.cs [hunk 1]
```diff
@@ -19,8 +19,8 @@ public static class CryptoHelper
     public static string GenerateAuthToken()
     {
         byte[] bytes = (byte[])GenerateRandomBytes(256);
-
-        return BCryptHash(Sha256Hash(bytes));
+
```
Comment (Slendy) [inline ProjectLighthouse/Helpers/CryptoHelper.cs:22]:
```suggestion

```
image
me when i see extra whitespace in a pr

**Review by Slendy — CHANGES_REQUESTED** [review]

File: ProjectLighthouse/Helpers/CryptoHelper.cs (hunk 1 above)
Comment (Zaprit) [reply ProjectLighthouse/Helpers/CryptoHelper.cs:22]: extra whitespace, bruh I meant to put that there :|

Comment (Zaprit) [reply ProjectLighthouse/Helpers/CryptoHelper.cs:22]: fine, but I'm not happy about it

File: ProjectLighthouse/Helpers/CryptoHelper.cs [hunk 2]
```diff
@@ -19,8 +19,7 @@ public static class CryptoHelper
     public static string GenerateAuthToken()
     {
         byte[] bytes = (byte[])GenerateRandomBytes(256);
-
-        return BCryptHash(Sha256Hash(bytes));
+        return Convert.ToBase64String(Encoding.UTF8.GetBytes(BCryptHash(Sha256Hash(bytes))));
```
Comment (sudokoko) [inline ProjectLighthouse/Helpers/CryptoHelper.cs:22]: Will this interfere with the game at all, or is this logic separate from game authentication tokens?

Comment (HenryAsbridge) [reply ProjectLighthouse/Helpers/CryptoHelper.cs:22]: It will likely cause re-auths for game players, I'll do a quick check to make sure that it won't affect anything persistent

Comment (Zaprit) [reply ProjectLighthouse/Helpers/CryptoHelper.cs:28]: I've just made it so that only tokens in emails are base64 encoded

**Review by sudokoko — APPROVED** [review]

**Review by Slendy — APPROVED** [review]
